export { default as AppEmail } from "./AppEmail";
export { default as AppFooter } from "./AppFooter";
export { default as AppNavigation } from "./AppNavigation";
export { default as AppSocials } from "./AppSocials";
export { default as AppHero } from "./AppSections/Hero";
export { default as AppAbout } from "./AppSections/About";
export { default as AppScroll } from "./AppScroll";
export { default as AppSkills } from "./AppSections/Skills";
export { default as AppExperience } from "./AppSections/Jobs";
// export {default as AppProjects} from "./AppSections/Projects";
// export {default as AppContact} from "./AppSections/Contact";
